os: Visual Studio 2015

branches:
  only:
    - master

platform:
  - Win32
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

environment:
  BOOST_ROOT: C:\Libraries\boost_1_62_0

install:
  - ps: if (-not (Test-Path tfs-sdk-3.2)) { Start-FileDownload https://static.otland.net/dl/tfs-sdk-3.2.zip; 7z x tfs-sdk-3.2.zip }
  - ps: if (-not (Test-Path tfs-sdk-3.2)) { Start-FileDownload https://static.otland.net/dl/tfs-sdk-3.2.zip; 7z x tfs-sdk-3.2.zip }
  - set TFSSDKDir=%CD%\tfs-sdk-3.2

cache:
  - tfs-sdk-3.2\make -> appveyor.yml
  - tfs-sdk-3.2\make_two -> appveyor.yml

artifacts:
  - path: make\vc14\**\theforgottenserver.exe
  - path: make_two\vc14\**\theforgottenserver.exe
