rateExp = 2
rateSkill = 9
rateLoot = 4
rateMagic = 3
rateSpawn = 1
killsToRedSkull = 5
killsToBlackSkull = 8
maxPlayers = 100
worldType = "PVP / RPG / CUSTOM"
protectionLevel = "NO"
removeAmmoWhenUsingDistanceWeapon = "YES"
timeToDecreaseFrags = "24 Hrs"
kickIdlePlayerAfterMinutes = "15 Mins"
whiteSkullTime = "15 Mins"
houseRentPeriod = "WEEKLY"
ownerName = "Mattyx14"
location = "Mexico"
ip = "darkkonia.sytes.net / 7171"
freePremium = "NO"
classicEquipmentSlots = "NO"
ownerEmail = "darkylive@live.com.mx"
enableLiveCasting = "NO"
