TOWNS_LIST = {
	FYNN_CASTLE = 1,
	ANSHARA_DESERT = 2,
	SOHAN_TOWN = 3,
	SAMARANSA_BAY = 4,
	FORGOS_VILLE = 5,
	AGARD_TOWN = 6,
	MER_JUNGLE = 7,
	VINOR_SWAMP = 8,
	JORVIK_VILLE = 9,
	MISIDIA_SETTLEMENT = 10,
	ELFIC_VILLE = 11,
	VAARGDON_MINE = 12,
	HIVE_ISLAND = 13,
	SUNKEN_SANCTUARY = 14
}
